version: '3'

services:
  server:
    build: "server/"
    environment:
      - PORT=${SERVER_PORT}
      - URL=${SERVER_URL}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./server/logs:/app/logs
